# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 37e6705a37b7b55e59c57773648c0a96cbc660be3bae98d300760d66f5ab80109254f3869b7fa2531b1b567cf6d4f9474c4ee64ab59e8b9efde491204d296462

test:
  secret_key_base: 871a322f8a5babaaf548a3e96f309625be47031b9273d2e8128a62367d00d40b7f57848eb00af77483dce7f7c318b2b617b2fa9ff171c94bacc5f96be36451c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
